version: '3.8'
x-environment-defaults: &environment-defaults
  DEBUG: "False"
  DB_NAME: "wisdom"
  DB_USER: "wisdom"
  DB_PASSWORD: "wisdom"
  DB_HOST: "wisdom-db"
  DB_PORT: 6432


services:
  wisdom-db:
    image: postgres:latest
    container_name: postgres
    environment:
      <<: *environment-defaults
#    environment:
#      POSTGRES_DB: wisdom
#      POSTGRES_USER: wisdom
#      POSTGRES_PASSWORD: wisdom
    ports:
      - "6432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - wisdom-network

volumes:
  pg_data:

networks:
  wisdom-network:
    driver: bridge