x-environment-defaults: &environment-defaults
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}
  TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
#  SECRET_KEY: ${SECRET_KEY}

services:

  wisdom:
    image: postgres:latest
    container_name: wisdom
    environment:
      <<: *environment-defaults
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - wisdom-network

  web:
    build:
      context: .
      dockerfile: admin_panel/Dockerfile
    container_name: django
    volumes:
      - .:/app
      - static_volume:/app/admin_panel/static  # Подключаем директорию для статики
    ports:
      - "8000:8000"
    networks:
      - wisdom-network
    depends_on:
      - wisdom

  tg:
    build:
      context: .  # Контекст сборки должен быть в корне проекта, а не внутри tg_bot
      dockerfile: tg_bot/Dockerfile
    container_name: tg
    environment:
      <<: *environment-defaults
    depends_on:
      - wisdom  # Ожидание, пока база данных будет готова
    networks:
      - wisdom-network
    restart: always  # Чтобы бот перезапускался, если что-то пойдет не так

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Путь до файла конфигурации
      - static_volume:/static  # Монтируем статику
    ports:
      - "80:80"
    networks:
      - wisdom-network
    depends_on:
      - web

volumes:
  pg_data:
  static_volume:

networks:
  wisdom-network:
    driver: bridge