# Generated by Django 5.1.4 on 2024-12-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tg_id", models.BigIntegerField(unique=True)),
                ("username", models.CharField(blank=True, null=True)),
                ("full_name", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Wisdoms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wisdom_text",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("author", models.CharField(blank=True, max_length=128, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "wisdoms",
                "managed": False,
            },
        ),
    ]
