"""Add column

Revision ID: 26060befedd0
Revises: d37af68dcfaa
Create Date: 2024-12-23 20:16:08.584781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26060befedd0'
down_revision: Union[str, None] = 'd37af68dcfaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wisdoms', sa.Column('author', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wisdoms', 'author')
    # ### end Alembic commands ###
