"""Rename column

Revision ID: de0a5e31604d
Revises: 26060befedd0
Create Date: 2024-12-23 21:03:33.050761

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de0a5e31604d"
down_revision: Union[str, None] = "26060befedd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wisdoms", sa.Column("wisdom_text", sa.String(length=128), nullable=True)
    )
    op.drop_column("wisdoms", "message")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wisdoms",
        sa.Column(
            "message", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("wisdoms", "wisdom_text")
    # ### end Alembic commands ###
