# Используем базовый образ Python
FROM python:3.12-slim

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем requirements.txt в контейнер
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь код приложения в контейнер
COPY . .

# Переменная окружения для отключения буферизации вывода
ENV PYTHONUNBUFFERED=1

# Указываем команду запуска приложения
CMD ["python", "bot.py"]